export const projects = [
  {
    title: 'Crypto Exchange App',
    description: "This crypto exchange app is built using React, Tailwind and Solidity. You can connect your crypto wallet and then can send crypto anywhere.",
    image: '/images/krypt.png',
    tags: ['React', 'Tailwindcss', 'Solidity'],
    source: 'https://kryptexchange.netlify.app',
    visit: 'https://github.com/Shahreyar00/React_BlockchainWeb3_App',
    id: 0,
  },
  {
    title: 'Image Sharing App',
    description:"You can post, download and comment on images. I designed it in Figma & then used that design with React to convert it into a functional webapp.",
    image: '/images/77.png',
    tags: ['React', 'Tailwindcss', 'React-icons'],
    source: 'https://usharee.netlify.app/',
    visit: 'https://github.com/Shahreyar00/UShareApp',
    id: 1,
  },
  {
    title: 'E-Commerce website UI',
    description: "This is a website built using react and styled-components. You can see register, signin, products and cart pages.",
    image: '/images/h7.png',
    tags: ['React', 'Styled-components'],
    source: 'https://ushoop.netlify.app',
    visit: 'https://github.com/Shahreyar00/Frontend_e-commerce',
    id: 2,
  },

  {
    title: 'Blog App',
    description: "This blog app is built using Next.js and GraphCMS. You can do all the CRUD operation in this using GraphCMS. ",
      image: '/images/blog.png',
      tags: ['Next.js', 'Express', 'GraphCMS', 'Node'],
    source: 'https://blog-app-using-graph-cms.vercel.app/',
    visit: 'https://github.com/Shahreyar00/BlogApp_using_GraphCMS_NextJs',
    id: 3,
  },

  {
    title: 'Modern UI Design',
    description:"This website is built using react and css. I designed it in Figma & then with React to convert it into a full website.",
    image: '/images/react.png',
    tags: ['React', 'CSS', 'React-icons'],
    source: 'https://modernui-react.netlify.app/',
    visit: 'https://github.com/Shahreyar00/ModernUI_Design',
    id: 4,
  },
  {
    title: 'Pizza Website UI',
    description: "This is a project showing Pizza website design UI. You can check cart and click on individual pizza. ",
    image: '/images/88.png',
    tags: ['Next.js', 'CSS'],
    source: 'https://nextjs-pizza-place-website.vercel.app/',
    visit: 'https://github.com/Shahreyar00/Nextjs_PizzaPlaceWebsite',
    id: 5,
  },
  {
    title: 'Website-Multi page',
    description: "This is a Multi page website build using Next.js. It's a demonstration of multi page design.",
    image: '/images/h6.png',
    tags: ['Next.js', 'CSS'],
    source: 'https://next-js-agencyui-website.vercel.app/',
    visit: 'https://github.com/Shahreyar00/NextJs_AgencyWebsite',
    id: 6,
  },
  {
    title: 'Portfolio website',
    description: "This is my other portfolio website build using React. It contains all the details and functional elements.",
    image: '/images/port2.png',
    tags: ['React', 'Scss'],
    source: 'https://shahreyar-portfolio.netlify.app/',
    visit: 'https://github.com/Shahreyar00/React_Personal_Portfolio',
    id: 7,
  },
  {
    title: 'Admin Dashboard',
    description: "This is an admnin dashboard which can be integrated with other apps.",
    image: '/images/h8.png',
    tags: ['React', 'CSS'],
    source: 'https://personal-admin-dashboard.netlify.app',
    visit: 'https://github.com/Shahreyar00/React_AdminDashboard',
    id: 8,
  },
  {
    title: 'RealEstate WebApp',
    description: "This is a real estate app which helps in finding the home to rent/buy.",
    image: '/images/h9.png',
    tags: ['Next.js', 'CSS'],
    source: 'https://next-js-your-home.vercel.app/',
    visit: 'https://github.com/Shahreyar00/NextJs_YourHome',
    id: 9,
  },
  {
    title: 'Portfolio MockUp',
    description: "This is another portfolio website which shows all the UI elements with some functional elements.",
    image: '/images/h10.png',
    tags: ['React', 'Scss'],
    source: 'https://react-demo-portfolio.netlify.app',
    visit: 'https://github.com/Shahreyar00/React_DemoPortfolio',
    id: 10,
  },
  {
    title: 'Restaurant Website',
    description: "This is a Restaurant website mockup with all the UI elements required and is styled using css.",
    image: '/images/gericht.png',
    tags: ['React', 'CSS'],
    source: 'https://restaurant-landing.netlify.app/',
    visit: 'https://github.com/Shahreyar00/React_RestaurantWebsite',
    id: 11,
  },
];

export const TimeLineData = [
  { year: 2015, text: 'Started my journey in the field of programming and learned C,C++ & Data Structure.', },
  { year: 2017, text: 'Completed my senior secondary education and took a year break for JEE preparation.', },
  { year: 2018, text: 'Got into Bachelor of Technology program majoring in Computer Science & Engineering and added Java as a new language.', },
  { year: 2019, text: 'This year started learning Python and Tensorflow. Experminented with various AI/ML methods and models.', },
  { year: 2020, text: 'Pandemic came and I focused my mind towards full-stack web development, Deeplearning and computer vision.', },
  { year: 2021, text: 'Currently working and growing my knowledge as full-stack web developer (MERN) and concurrently learning Reinforcement learning.', },
];